INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Никонова', 'Лайма', 'Аристарховна', '+7(929)580-04-74');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Караваев', 'Игорь', 'Петрович', '+7(961)835-17-49');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Васнецов', 'Всеволод', 'Артемьевич', '+7(902)198-60-62');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Жилина', 'Светлана', 'Владимировна', '+7(909)353-70-46');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Волошина', 'Алёна', 'Игоревна', '+7(927)668-14-40');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Дроздова', 'Розалия', 'Львовна', '+7(940)840-32-75');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Фирсов', 'Евгений', 'Михайлович', '+7(046)787-84-23');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Кудрявцев', 'Эрнест', 'Лукьевич', '+7(908)416-12-99');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Трофимов', 'Лев', 'Васильевич', '+7(872)256-42-68');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Белоусова', 'Валерия', 'Евгеньевна', '+7(846)291-75-07');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Ермаков', 'Александр', 'Алексеевич', '+7(987)883-16-96');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Ермаков', 'Святослав', 'Александрович', '+7(987)536-05-70');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Сысоев', 'Гавриил', 'Геннадьевич', '+7(987)238-07-86');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Казаков', 'Аввакуум', 'Рубенович', '+7(961)536-05-70');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Романов', 'Юрий', 'Святославович', '+7(909)698-21-78');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Тихонов', 'Мечислав', 'Филиппович', '+7(910)195-56-79');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Никонова', 'Генриетта', 'Александровна', '+7(961)656-99-80');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Воронова', 'Полина', 'Антониновна', '+7(937)957-77-29');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Сорокина', 'Моника', 'Антоновна', '+7(917)418-32-62');
INSERT INTO PATIENT (LAST_NAME, FIRST_NAME, PATRONYMIC, PHONE_NUMBER)
VALUES ('Власова', 'Алла', 'Иринеевна', '+7(956)627-53-33');



INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Беляева', 'Анна', 'Андреевна', 'Терапевт');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Абрамов', 'Вячеслав', 'Андреевич', 'Стоматолог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Антонова', 'Муза', 'Данииловна', 'Терапевт');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Косарев', 'Николай', 'Егорович', 'Гинеколог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Кулешова', 'Алина', 'Тимуровна', 'Невролог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Харитонов', 'Илья', 'Петрович', 'Отоларинголог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Артемьева', 'Марианна', 'Викторовна', 'Невропатолог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Медведева', 'Елена', 'Богдановна', 'Окулист');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Новиков', 'Григорий', 'Никитич', 'Психиатр');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Ефремова', 'Марина', 'Владиславовна', 'Окушер');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Кулагина', 'Лана', 'Тихоновна', 'Уролог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Михеева', 'Виргиния', 'Валерьяновна', 'Стомалотог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Лебедев', 'Людвиг', 'Федотович', 'Хирург');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Захаров', 'Юлий', 'Ростиславович', 'Кардиолог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Кузнецов', 'Вилли', 'Агафонович', 'Иммунолог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Носов', 'Леонард', 'Аркадьевич', 'Терапевт');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Осипова', 'Феодосия', 'Тимофеевна', 'Онколог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Ершова', 'Изольда', 'Сергеевна', 'Хирург');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Мышкина', 'Анастасия', 'Мироновна', 'Эндокринолог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Силина', 'Ярослава', 'Всеволодовна', 'Окулист');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Тарасова', 'Амира', 'Протасьевна', 'Аллерголог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Терентьева', 'Элиза', 'Аркадьевна', 'Дерматолог');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Куликова', 'Магда', 'Авдеевна', 'Инфекционист');
INSERT INTO DOCTOR (LAST_NAME, FIRST_NAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Кулакова', 'Залина', 'Игоревна', 'Пульмонолог');


INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Цистамин', '0', '0', '2020-07-31', '7', 'Нормальный');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Холина салицилат', '1', '1', '2020-07-15', '30', 'Нормальный');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Хинидин', '2', '2', '2020-05-30', '180', 'Нормальный');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Аллоксим', '6', '4', '2020-07-28', '15', 'Cito');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Агомелатин', '11', '1', '2020-08-01', '30', 'Cito');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Фтивазид', '19', '1', '2020-08-01', '30', 'Нормальный');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Цефаксон', '15', '15', '2020-08-01', '30', 'Нормальный');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Цефелим', '7', '19', '2020-08-01', '30', 'Statim');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Фунзол', '18', '11', '2020-08-01', '30', 'Cito');
INSERT INTO PRESCRIPTION (DESCRIPTION, PATIENT_ID, DOCTOR_ID, DATE_CREAT, VALIDITY_PERIOD, PRIORITY)
VALUES ('Эмбермин', '8', '4', '2020-08-01', '30', 'Нормальный');